{% set name = "ipecharts" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipecharts-{{ version }}.tar.gz
  sha256: 43116b22dc4683f0080d0c8d859ba797e41037fec73c08ac77612e50cecea80b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - nodejs
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
    - pip
    - markdownify
    - autodoc-traits
    - ruff
    - sphinx
  run:
    - python >={{ python_min }}
    - ipywidgets >=8

test:
  imports:
    - ipecharts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trungleduc/ipecharts
  summary: Apache Echarts Jupyter Widget.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trungleduc
