{% set name = "ipecharts" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipecharts-{{ version }}.tar.gz
  sha256: 260118e071b12cc823b95b3a57c3579112b3322b5a9fd6993d40952360c3149d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - nodejs
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
    - pip
    - markdownify
    - autodoc-traits
    - ruff
    - sphinx
  run:
    - python >=3.8
    - ipywidgets >=8

test:
  imports:
    - ipecharts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trungleduc/ipecharts
  summary: Apache Echarts Jupyter Widget.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trungleduc
